#!/usr/bin/env python3
from os import path

import click

import video_commands_lib as vlc

@click.command()
@click.argument('image_src')
@click.argument('image_dst', default='')
def removebg(image_src, image_dst):
    """Remove background from image"""
    if not image_src:
        click.echo('You need to indicate an image to remove background.')
    else:
        try:
            output = vlc.remove_background(image_src, image_dst)
            if path.isfile(path.join(path.dirname(image_src), output)):
                click.echo(f"The file {output} has been created successfully.")
            else:
                click.echo(f"Something went wrong when creating the file {output}.")
                click.echo(f"Please check that {image_src} is an image file.")
        except ImportError:
            click.echo('The "rembg" module is not installed. Please install it first: ')
            click.echo('\tpip install rembg')

if __name__ == '__main__':
    removebg()
