#!/usr/bin/env python3

from pathlib import Path

import click
import colorama
from PIL import Image, ImageFont, ImageDraw
import textwrap
import yaml

from video_commands_lib import normalize_color, normalize_size, list_fonts, path_to_font, calculate_text_position
import text_effects_on_images as text_effects

default_width = 1920
default_height = 1080
default_size = f"{default_width}x{default_height}"

@click.group()
def cli():
    pass

@cli.command()
@click.option('--width', type=int, default=0, help='Canvas width')
@click.option('--height', type=int, default=0, help='Canvas height')
@click.option('--x', type=int, default=0, help='Horizontal position of the beginning of writing')
@click.option('--y', type=int, default=0, help='Vertical position of the beginning of writing')
@click.option('--size', default="", help='Canvas height')
@click.option('--bgcolor', default='white', help='Color of the background (name or hexadecimal code)')
@click.option('--color', default='black', help='Color of the text (name or hexadecimal code)')
@click.option('--text', default='Lorem Ipsum', help='Text to write.')
@click.option('--font', help='Typography with which to write the text.')
@click.option('--font_size', type=int, default=20, help='Size of letters')
@click.option('--max_chars_line', type=int, default=20, help='Maximum number of characters per line.')
@click.option('--text_size', type=int, default=default_width * 80 // 100, help='size of the sign to write on the image, in case --font-size is not indicated')
@click.option('--gravity', default='C', help='sign position: N, NE, E, SE, S, SW, W, NW or C (North, North-East, East, South, South-West, West, North-West o Center)')
@click.option('--margin', type=int, default=0, help='margin with respect to the gravity point')
@click.option('--config', help='Path to config file')
@click.option('--effect', help='Effect on letters')
@click.option('--input', help='Path to input file')
@click.option('--output', default='sign.png', help='Path to output file')
def new(width, height, x, y, size, bgcolor, color, text, font, font_size, max_chars_line, text_size, gravity, margin, config, effect, input, output):
    """ Create a new image file with the indicated text. """

    # TODO: Delete input option

    if config:
        with open(config, 'r') as f:
            config_data = yaml.safe_load(f)

        for key, value in config_data.items():
            width = value.get('width', 0)
            height = value.get('height', 0)
            x = value.get('x', 0)
            y = value.get('y', 0)
            size = value.get('size', '')
            bgcolor = value.get('bgcolor', 'white')
            color = value.get('color', 'black')
            text = value.get('text', 'Lorem Ipsum')
            font = value.get('font', None)
            font_size = value.get('font_size', 20)
            text_size = value.get('text_size', default_width * 80 // 100)
            gravity = value.get('gravity', 'C')
            margin = value.get('margin', 0)
            effect = value.get('effect', None)
            output = f"{key}.png"

    bgcolor = normalize_color(bgcolor)
    color = normalize_color(color)
    width, height = normalize_size(width, height, size, default_width, default_height)
    print(width, height, x, y, size, bgcolor, color, text, font, font_size, text_size, gravity, margin, config, effect, input, output)

    if font:
        font_path = path_to_font(font)
        if font_path:
            font_var = ImageFont.truetype(font_path, font_size)
        else:
            font_var = ImageFont.load_default()
    else:
        font_var = ImageFont.load_default()

    img = Image.new('RGB', (width, height), color=bgcolor)
    text_layer = Image.new('RGBA', (width, height), color=(0, 0, 0, 0))
    draw = ImageDraw.Draw(text_layer)

    text_x, text_y = calculate_text_position(width, height, margin, gravity, text, font_var, draw)
    lines = textwrap.wrap(text, width=max_chars_line)

    line_height = font_var.getsize(' ')[1]

    for count, line in enumerate(lines):
        text_x, text_y = calculate_text_position(width, height, margin, gravity, line, font_var, draw)
        text_y += line_height * count
        line_width, line_height = draw.textsize(line, font=font_var)
        draw.text((text_x, text_y), line, fill=color, font=font_var)

    if effect:
        text_layer = text_effects.apply_effect(text_layer, font_size, effect)

    img.paste(text_layer, (0, 0), text_layer)
    img.save(output)
    output_path = Path(output)
    if output_path.is_file():
        click.echo(f"The image has been created{ colorama.Fore.GREEN } successfully{ colorama.Style.RESET_ALL }: {output}")
    else:
        click.echo(f"An{ colorama.Fore.RED } error{ colorama.Style.RESET_ALL } occurred creating the file {output}.")

@cli.command()
def simple():
    """ """
    pass

@cli.command()
def wordbyword():
    """ """
    pass

@cli.command()
def animated():
    """ """
    pass

@cli.command()
def typewriter():
    """ """
    pass

@cli.command()
@click.argument('element')
def list(element):
    """Lists the elements available to work with the command."""
    if element.lower() == "fonts":
        list_fonts()
    elif element.lower() == "effects":
        text_effects.list_effects()

if __name__ == '__main__':
    cli()
